# Configuration for the RNA-seq pipeline

# Experiment ID to process
experiment_id: "250418_RNA-seq"

# Optional: Override default file paths or parameters here
# counts_file_template: "data/{exp_id}/counts.tsv"
# metadata_file_template: "data/{exp_id}/metadata.csv"
# gene_id_column: "GeneID"
# sample_id_column: "SampleID" 

# biomaRt settings (required for R01_create_se)
biomart_dataset: "hsapiens_gene_ensembl" # For human experiment 
